name: C2D - Major Functionality Test

on:
  repository_dispatch:
    types: [run-major-tests,run-nightly-major-tests]
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'prod'
      branch:
        description: 'Branch to test'
        required: true
        default: 'main'

permissions:
  contents: read

jobs:
  run-major-test:
    name: Run Major Spec File
    runs-on: ubuntu-latest
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch || github.event.inputs.branch }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Set environment
        run: |
          if [[ "${{ github.event.client_payload.env || github.event.inputs.env }}" == "prod" ]]; then
            echo "CYPRESS_API_BASE_URL=https://api.click2deploy.com/api/v1" >> $GITHUB_ENV
            echo "CYPRESS_PROJECT_URL=https://click2deploy.com/project" >> $GITHUB_ENV
            echo "CYPRESS_HOME_URL=https://click2deploy.com/" >> $GITHUB_ENV
          else
            echo "CYPRESS_API_BASE_URL=https://dev-backend.click2deploy.com/api/v1" >> $GITHUB_ENV
            echo "CYPRESS_PROJECT_URL=https://dev.click2deploy.com/project" >> $GITHUB_ENV
            echo "CYPRESS_HOME_URL=https://dev.click2deploy.com/" >> $GITHUB_ENV
          fi

      - name: Run Cypress tests (record to Cypress Cloud + mochawesome)
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/C2D/EnhanceApproach/01_NewUI_E2E.cy.js
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Upload Mochawesome report
        if: always() # ensures upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results-major
          path: cypress/reports/mochawesome/*.json
