name: Cypress Test via Dispatch

on:
  repository_dispatch:
    types: [run-e2e-tests]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout correct branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch }}

      - name: Install dependencies and build project
        run: |
          npm install --legacy-peer-deps
          npm run build
        env:
          NEXT_PUBLIC_STRIPE_PUBLIC_KEY: "pk_test_placeholder"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          group: 'ci-group'
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_API_BASE_URL: ${{ github.event.client_payload.env == 'prod' && secrets.PROD_API_URL || secrets.DEV_API_URL }}
          CYPRESS_PROJECT_URL: ${{ github.event.client_payload.env == 'prod' && secrets.PROD_PROJECT_URL || secrets.DEV_PROJECT_URL }}
          CYPRESS_HOME_URL: ${{ github.event.client_payload.env == 'prod' && secrets.PROD_HOME_URL || secrets.DEV_HOME_URL }}
