name: Master C2D E2E Dispatcher (Sequential)

on:
  repository_dispatch:
    types: [run-e2e-tests]

permissions:
  contents: read
  actions: write

jobs:
  dispatch-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GH CLI
        run: gh auth login --with-token <<< "${{ secrets.CYPRESS_TRIGGER_TOKEN }}"

      # Function to trigger & wait
      - name: Create trigger script
        run: |
          cat <<'EOF' > trigger_and_wait.sh
          #!/bin/bash
          WF_NAME="$1"
          echo "Triggering: $WF_NAME"
          run_id=$(gh workflow run "$WF_NAME" \
            --repo Click2Deploy/c2d-tests \
            --ref "${{ github.event.client_payload.branch }}" \
            -f env="${{ github.event.client_payload.env }}" \
            --json run_id --jq .run_id)

          echo "Waiting for workflow '$WF_NAME' (run_id=$run_id) to finish..."
          while true; do
            status=$(gh run view $run_id --repo Click2Deploy/c2d-tests --json status --jq .status)
            conclusion=$(gh run view $run_id --repo Click2Deploy/c2d-tests --json conclusion --jq .conclusion)
            if [ "$status" == "completed" ]; then
              echo "Result: $conclusion"
              [ "$conclusion" = "success" ] || exit 1
              break
            fi
            sleep 30
          done
          EOF
          chmod +x trigger_and_wait.sh

      # 1. Major Functionality Test
      - run: ./trigger_and_wait.sh "C2D - Major Functionality Test"

      # 2. Other Functionality Test
      - run: ./trigger_and_wait.sh "C2D - Other Functionality Test"

      # 3. Delete Project Test (First Run)
      - run: ./trigger_and_wait.sh "C2D - Deleting All Projects"

      # 4. Odoo Versions Test
      - run: ./trigger_and_wait.sh "C2D - Odoo Versions Test"

      # 5. Delete Project Test (Second Run)
      - run: ./trigger_and_wait.sh "C2D - Deleting All Projects"
