name: Master C2D E2E Dispatcher (Parallel)

on:
  repository_dispatch:
    types: [run-e2e-tests]

permissions:
  contents: read
  actions: write

jobs:
  setup-script:
    runs-on: ubuntu-22.04
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GH CLI
        run: gh auth login --with-token <<< "${{ secrets.CYPRESS_TRIGGER_TOKEN }}"

      - name: Save trigger script
        run: |
          cat <<'EOF' > trigger_and_wait.sh
          #!/bin/bash
          WF_NAME="$1"
          echo "Triggering: $WF_NAME"

          gh workflow run "$WF_NAME" \
            --repo Click2Deploy/c2d-tests \
            --ref "${{ github.event.client_payload.branch }}" \
            -f env="${{ github.event.client_payload.env }}"
          EOF
          chmod +x trigger_and_wait.sh

      - name: Upload script
        uses: actions/upload-artifact@v4
        with:
          name: trigger-script
          path: trigger_and_wait.sh

  major-functionality:
    runs-on: ubuntu-22.04
    needs: setup-script
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: trigger-script
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh
      - name: Authenticate GH CLI
        run: gh auth login --with-token <<< "${{ secrets.CYPRESS_TRIGGER_TOKEN }}"
      - run: bash trigger_and_wait.sh "C2D - Major Functionality Test"

  other-functionality:
    runs-on: ubuntu-22.04
    needs: setup-script
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: trigger-script
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh
      - name: Authenticate GH CLI
        run: gh auth login --with-token <<< "${{ secrets.CYPRESS_TRIGGER_TOKEN }}"
      - run: bash trigger_and_wait.sh "C2D - Other Functionality Test"

  odoo-versions:
    runs-on: ubuntu-22.04
    needs: setup-script
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: trigger-script
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh
      - name: Authenticate GH CLI
        run: gh auth login --with-token <<< "${{ secrets.CYPRESS_TRIGGER_TOKEN }}"
      - run: bash trigger_and_wait.sh "C2D - Odoo Versions Test"
