name: C2D - Odoo Versions Test

on:
  repository_dispatch:
    types: [run-odoo-test]
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'
      branch:
        description: 'Branch to test'
        required: true
        default: 'dev'

permissions:
  contents: read

jobs:
  run-odoo:
    name: Run Odoo Versions Spec
    runs-on: ubuntu-latest
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch || github.event.inputs.branch }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Set environment
        run: |
          if [[ "${{ github.event.client_payload.env || github.event.inputs.env }}" == "prod" ]]; then
            echo "CYPRESS_API_BASE_URL=https://api.click2deploy.com/api/v1" >> $GITHUB_ENV
            echo "CYPRESS_PROJECT_URL=https://click2deploy.com/project" >> $GITHUB_ENV
            echo "CYPRESS_HOME_URL=https://click2deploy.com/" >> $GITHUB_ENV
          else
            echo "CYPRESS_API_BASE_URL=https://dev-backend.click2deploy.com/api/v1" >> $GITHUB_ENV
            echo "CYPRESS_PROJECT_URL=https://dev.click2deploy.com/project" >> $GITHUB_ENV
            echo "CYPRESS_HOME_URL=https://dev.click2deploy.com/" >> $GITHUB_ENV
          fi

      - name: Run Cypress tests (record to Cypress Cloud)
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/C2D/EnhanceApproach/06_NewUI_validate_Odoo_all_Versions.cy.js
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Save job result
        if: always()
        run: |
          echo "result=${{ job.status }}" >> $GITHUB_ENV

      - name: Notify Slack - Odoo Versions Test
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "*C2D - Odoo Versions Test* finished with *${{ job.status }}* :\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Trigger Delete All Projects workflow
        if: always() # runs even if Cypress fails
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.REPO_DISPATCH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"run-delete-project-test","client_payload":{"env":"${{ github.event.client_payload.env || github.event.inputs.env }}","branch":"${{ github.event.client_payload.branch || github.event.inputs.branch }}"}}'
