name: C2D - Odoo Versions Test

on:
  repository_dispatch:
    types: [run-odoo-test]
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'
      branch:
        description: 'Branch to test'
        required: true
        default: 'dev'

permissions:
  contents: read

jobs:
  run-odoo:
    name: Run Odoo Versions Spec
    runs-on: ubuntu-latest
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch || github.event.inputs.branch }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Set environment
        run: |
          if [[ "${{ github.event.client_payload.env || github.event.inputs.env }}" == "prod" ]]; then
            echo "CYPRESS_API_BASE_URL=https://api.click2deploy.com/api/v1" >> $GITHUB_ENV
            echo "CYPRESS_PROJECT_URL=https://click2deploy.com/project" >> $GITHUB_ENV
            echo "CYPRESS_HOME_URL=https://click2deploy.com/" >> $GITHUB_ENV
          else
            echo "CYPRESS_API_BASE_URL=https://dev-backend.click2deploy.com/api/v1" >> $GITHUB_ENV
            echo "CYPRESS_PROJECT_URL=https://dev.click2deploy.com/project" >> $GITHUB_ENV
            echo "CYPRESS_HOME_URL=https://dev.click2deploy.com/" >> $GITHUB_ENV
          fi

      - name: Run Cypress tests and save report
        id: cypress
        run: |
          npx cypress run \
            --spec cypress/e2e/C2D/EnhanceApproach/06_NewUI_validate_Odoo_all_Versions.cy.js \
            --reporter mochawesome \
            --reporter-options "reportDir=cypress/reports,overwrite=false,html=false,json=true" || true

          # Ensure results.json always exists
          if [ -f cypress/reports/mochawesome*.json ]; then
            cp cypress/reports/mochawesome*.json results.json
          else
            echo '{"stats":{"tests":0,"passes":0,"failures":0},"results":[]}' > results.json
          fi


      - name: Parse Cypress results
        if: always()
        run: |
          passed=$(jq '[.runs[].tests[] | select(.state=="passed")] | length' results.json)
          failed=$(jq '[.runs[].tests[] | select(.state=="failed")] | length' results.json)
          total=$(jq '[.runs[].tests[]] | length' results.json)
          failedTests=$(jq -r '[.runs[].tests[] | select(.state=="failed") | .title | join(" ")]' results.json | tr -d '\n')

          echo "passed=$passed" >> $GITHUB_ENV
          echo "failed=$failed" >> $GITHUB_ENV
          echo "total=$total" >> $GITHUB_ENV
          echo "failedTests=$failedTests" >> $GITHUB_ENV

      - name: Notify Slack - Odoo Versions Test
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "*C2D - Odoo Versions Test Finished*\nBranch: ${{ github.event.client_payload.branch || github.event.inputs.branch }}\nEnvironment: ${{ github.event.client_payload.env || github.event.inputs.env }}\nTests: ${{ env.total }} | ✅ ${{ env.passed }} | ❌ ${{ env.failed }}\nFailed Tests: ${{ env.failedTests }}\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Trigger Delete All Projects workflow
        if: always()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.REPO_DISPATCH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"run-delete-project-test","client_payload":{"env":"${{ github.event.client_payload.env || github.event.inputs.env }}","branch":"${{ github.event.client_payload.branch || github.event.inputs.branch }}"}}'
