name: C2D - Other Functionality Test

on:
  repository_dispatch:
    types: [run-other-tests]
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'
      branch:
        description: 'Branch to test'
        required: true
        default: 'dev'

permissions:
  contents: read

jobs:
  run-other-specs:
    name: Run Spec Files 02 & 05
    runs-on: ubuntu-latest
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch || github.event.inputs.branch }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Set environment
        run: |
          if [[ "${{ github.event.client_payload.env || github.event.inputs.env }}" == "prod" ]]; then
            echo "CYPRESS_API_BASE_URL=https://api.click2deploy.com/api/v1" >> $GITHUB_ENV
            echo "CYPRESS_PROJECT_URL=https://click2deploy.com/project" >> $GITHUB_ENV
            echo "CYPRESS_HOME_URL=https://click2deploy.com/" >> $GITHUB_ENV
          else
            echo "CYPRESS_API_BASE_URL=https://dev-backend.click2deploy.com/api/v1" >> $GITHUB_ENV
            echo "CYPRESS_PROJECT_URL=https://dev.click2deploy.com/project" >> $GITHUB_ENV
            echo "CYPRESS_HOME_URL=https://dev.click2deploy.com/" >> $GITHUB_ENV
          fi

      - name: Run Cypress tests (record to Cypress Cloud)
        uses: cypress-io/github-action@v6
        with:
          # Comma-separated, no trailing commas
          spec: cypress/e2e/C2D/EnhanceApproach/02_NewUI_merging_branches_on_different_stages.cy.js,cypress/e2e/C2D/EnhanceApproach/05_NewUI_create_project_using_existing_repo.cy.js
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Trigger Slack Notifications-Proceed workflow
        if: always() # runs even if Cypress fails
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.REPO_DISPATCH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"run-notification-proceed","client_payload":{"workflow":"C2D - Other Functionality Test","env":"${{ github.event.client_payload.env || github.event.inputs.env }}","branch":"${{ github.event.client_payload.branch || github.event.inputs.branch }}"}}'
