name: Slack Notifications-Proceed workflow

on:
  workflow_run:
    workflows: 
      - "C2D - Odoo Versions Test"
      - "C2D - Deleting All Projects"
      - "C2D - Major Functionality Test"
      - "C2D - Other Functionality Test"
      - "Slack - Notification Test"
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: cypress-results
          path: results

      - name: Parse test results
        id: parse
        run: |
          if [ -f results/results.json ]; then
            TOTAL=$(jq '.stats.tests' results/results.json)
            PASSED=$(jq '.stats.passes' results/results.json)
            FAILED=$(jq '.stats.failures' results/results.json)

            echo "TOTAL=$TOTAL" >> $GITHUB_ENV
            echo "PASSED=$PASSED" >> $GITHUB_ENV
            echo "FAILED=$FAILED" >> $GITHUB_ENV

            FAILED_LIST=$(jq -r '.tests[] | select(.state=="failed") | .title | join(" - ")' results/results.json)
            if [ -n "$FAILED_LIST" ]; then
              FAILED_LIST=$(echo "$FAILED_LIST" | sed 's/^/* /')
              echo "FAILED_TESTS=$FAILED_LIST" >> $GITHUB_ENV
            else
              echo "FAILED_TESTS=" >> $GITHUB_ENV
            fi
          else
            echo "TOTAL=0" >> $GITHUB_ENV
            echo "PASSED=0" >> $GITHUB_ENV
            echo "FAILED=0" >> $GITHUB_ENV
            echo "FAILED_TESTS=" >> $GITHUB_ENV
          fi

      - name: Send Slack notification
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
            MSG=":white_check_mark: Workflow *${{ github.event.workflow.name }}* succeeded for branch *${{ github.event.workflow_run.head_branch }}* (by ${{ github.event.workflow_run.actor.login }})."
          else
            MSG=":x: Workflow *${{ github.event.workflow.name }}* failed for branch *${{ github.event.workflow_run.head_branch }}* (by ${{ github.event.workflow_run.actor.login }})."
          fi

          STATS="Tests: $TOTAL | :white_check_mark: $PASSED | :x: $FAILED"

          if [ -n \"$FAILED_TESTS\" ]; then
            DETAILS="\n*Failed tests:*\n$FAILED_TESTS"
          else
            DETAILS=""
          fi

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MSG\n$STATS$DETAILS\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
