name: Slack - Notification Test

on:
  repository_dispatch:
    types: [run-notification-test]
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: 'dev'
      branch:
        description: 'Branch to test'
        required: true
        default: 'dev'

permissions:
  contents: read

jobs:
  run-notification-test:
    name: Run Notification Spec File
    runs-on: ubuntu-latest
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch || github.event.inputs.branch }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install reporters (CI only)
        run: npm install --no-save mocha mocha-multi-reporters mochawesome mochawesome-merge

      - name: Set environment
        run: |
          if [[ "${{ github.event.client_payload.env || github.event.inputs.env }}" == "prod" ]]; then
            echo "CYPRESS_API_BASE_URL=https://api.click2deploy.com/api/v1" >> $GITHUB_ENV
            echo "CYPRESS_PROJECT_URL=https://click2deploy.com/project" >> $GITHUB_ENV
            echo "CYPRESS_HOME_URL=https://click2deploy.com/" >> $GITHUB_ENV
          else
            echo "CYPRESS_API_BASE_URL=https://dev-backend.click2deploy.com/api/v1" >> $GITHUB_ENV
            echo "CYPRESS_PROJECT_URL=https://dev.click2deploy.com/project" >> $GITHUB_ENV
            echo "CYPRESS_HOME_URL=https://dev.click2deploy.com/" >> $GITHUB_ENV
          fi

      - name: Run Cypress Notification Test
        run: |
          npx cypress run \
            --spec "cypress/e2e/C2D/EnhanceApproach/51_Notification_test.cy.js" \
            --reporter mocha-multi-reporters \
            --reporter-options configFile=reporter-config.json

      - name: Merge Mochawesome reports
        if: always()
        run: npx mochawesome-merge "cypress/reports/*.json" > results.json

      - name: Upload Cypress results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/reports/*.json

      - name: Send Slack notification
        if: always()
        run: |
          total=$(jq '.stats.tests' results.json)
          passes=$(jq '.stats.passes' results.json)
          failures=$(jq '.stats.failures' results.json)

          failed_tests=$(jq -r '.results[].suites[].tests[] | select(.state=="failed") | .fullTitle' results.json)

          message="*Slack - Notification Test Finished*\n
          *Branch:* ${{ github.event.inputs.branch || github.event.client_payload.branch }}\n
          *Environment:* ${{ github.event.inputs.env || github.event.client_payload.env }}\n
          *Tests:* $total | ✅ $passes | ❌ $failures\n
          *Failed Tests:*\n$failed_tests"

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"$message\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
