name: Slack - Notification Test

on:
  push:
    branches:
      - main
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --reporter cypress-mochawesome-reporter --reporter-options overwrite=false,html=false,json=true

      - name: Upload mochawesome results
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/reports/.jsons
