name: Slack Notifications-Proceed

on:
  workflow_dispatch:
  repository_dispatch:
    types: [send-slack-report]

jobs:
  send-slack-report:
    runs-on: ubuntu-latest

    steps:
      - name: Download Cypress results artifact
        uses: actions/download-artifact@v4
        with:
          name: cypress-results
          path: ./results

      - name: Install reporters
        run: npm install --no-save mochawesome mochawesome-merge

      - name: Merge test reports
        run: npx mochawesome-merge "results/*.json" > merged-report.json

      - name: Parse results and send to Slack
        run: |
          PASSED=$(jq '[.results[].suites[].tests[] | select(.pass==true)] | length' merged-report.json)
          FAILED=$(jq '[.results[].suites[].tests[] | select(.fail==true)] | length' merged-report.json)
          FAILED_TESTS=$(jq -r '[.results[].suites[].tests[] | select(.fail==true) | .fullTitle] | join("\n- ")' merged-report.json)

          if [ "$FAILED" -gt 0 ]; then
            STATUS="❌ $FAILED test(s) failed"
          else
            STATUS="✅ All $PASSED tests passed"
          fi

          MESSAGE="*Cypress Test Results*\n$STATUS\n\n*Passed:* $PASSED\n*Failed:* $FAILED"

          if [ "$FAILED" -gt 0 ]; then
            MESSAGE="$MESSAGE\n\n*Failed Tests:*\n- $FAILED_TESTS"
          fi

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"$MESSAGE\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
