name: Slack Notifications-Proceed

on:
  workflow_run:
    workflows: ["Slack - Notification Test"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: cypress-results
          path: results-raw

      - name: Merge mochawesome reports
        run: |
          mkdir -p results
          npx mochawesome-merge results-raw/cypress/reports/.jsons/*.json > results/results.json

      - name: Prepare Slack message
        id: slack
        run: |
          total=$(jq '.stats.tests' results/results.json)
          passes=$(jq '.stats.passes' results/results.json)
          failures=$(jq '.stats.failures' results/results.json)

          # collect failed test titles
          failed_tests=$(jq -r '.results[].suites[].tests[] | select(.fail) | .title' results/results.json | xargs -0)

          echo "total=$total" >> $GITHUB_ENV
          echo "passes=$passes" >> $GITHUB_ENV
          echo "failures=$failures" >> $GITHUB_ENV
          echo "failed_tests=$failed_tests" >> $GITHUB_ENV

      - name: Send Slack notification
        run: |
          payload="{
            \"text\": \"*Cypress Test Report* (Workflow: ${{ github.workflow }}, Branch: ${{ github.event.workflow_run.head_branch }})\nTotal: ${{ env.total }} | ✅ Passed: ${{ env.passes }} | ❌ Failed: ${{ env.failures }}\",
            \"attachments\": [
              {
                \"color\": \"#ff0000\",
                \"text\": \"*Failed Tests:* \n${{ env.failed_tests }}\"
              }
            ]
          }"

          curl -X POST -H 'Content-type: application/json' \
            --data "$payload" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
