name: Slack Notification Test

on:
  workflow_dispatch:

jobs:
  test-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a success message
        run: echo "✅ This is a test to check Slack notification from GitHub Actions"
